// Code generated by 'go generate'; DO NOT EDIT.

package tftp

import (
	"syscall"
	"unsafe"

	"golang.org/x/sys/windows"
)

var _ unsafe.Pointer

// Do the interface allocations only once for common
// Errno values.
const (
	errnoERROR_IO_PENDING = 997
)

var (
	errERROR_IO_PENDING error = syscall.Errno(errnoERROR_IO_PENDING)
	errERROR_EINVAL     error = syscall.EINVAL
)

// errnoErr returns common boxed Errno values, to prevent
// allocations at runtime.
func errnoErr(e syscall.Errno) error {
	switch e {
	case 0:
		return errERROR_EINVAL
	case errnoERROR_IO_PENDING:
		return errERROR_IO_PENDING
	}
	// TODO: add more here, after collecting data on the common
	// error values see on Windows. (perhaps when running
	// all.bat?)
	return e
}

var (
	modqwave = windows.NewLazySystemDLL("qwave.dll")

	procQOSAddSocketToFlow      = modqwave.NewProc("QOSAddSocketToFlow")
	procQOSCloseHandle          = modqwave.NewProc("QOSCloseHandle")
	procQOSCreateHandle         = modqwave.NewProc("QOSCreateHandle")
	procQOSRemoveSocketFromFlow = modqwave.NewProc("QOSRemoveSocketFromFlow")
	procQOSSetFlow              = modqwave.NewProc("QOSSetFlow")
)

func winQoSAddSocketToFlow(qosHandle windows.Handle, socket windows.Handle, destAddr unsafe.Pointer, trafficType uint32, flags uint32, flowId *uint32) (ok bool, err error) {
	r0, _, e1 := syscall.SyscallN(procQOSAddSocketToFlow.Addr(), uintptr(qosHandle), uintptr(socket), uintptr(destAddr), uintptr(trafficType), uintptr(flags), uintptr(unsafe.Pointer(flowId)))
	ok = r0 != 0
	if ok == false {
		err = errnoErr(e1)
	}
	return
}

func winQoSCloseHandle(qosHandle windows.Handle) (ok bool, err error) {
	r0, _, e1 := syscall.SyscallN(procQOSCloseHandle.Addr(), uintptr(qosHandle))
	ok = r0 != 0
	if ok == false {
		err = errnoErr(e1)
	}
	return
}

func winQoSCreateHandle(clientVersion unsafe.Pointer, qosHandle *windows.Handle) (ok bool, err error) {
	r0, _, e1 := syscall.SyscallN(procQOSCreateHandle.Addr(), uintptr(clientVersion), uintptr(unsafe.Pointer(qosHandle)))
	ok = r0 != 0
	if ok == false {
		err = errnoErr(e1)
	}
	return
}

func winQoSRemoveSocketFromFlow(qosHandle windows.Handle, socket windows.Handle, flowId uint32, flags uint32) (ok bool, err error) {
	r0, _, e1 := syscall.SyscallN(procQOSRemoveSocketFromFlow.Addr(), uintptr(qosHandle), uintptr(socket), uintptr(flowId), uintptr(flags))
	ok = r0 != 0
	if ok == false {
		err = errnoErr(e1)
	}
	return
}

func winQoSSetFlow(qosHandle windows.Handle, flowId uint32, operation uint32, size uint32, buffer unsafe.Pointer, flags uint32, overlapped *windows.Overlapped) (ok bool, err error) {
	r0, _, e1 := syscall.SyscallN(procQOSSetFlow.Addr(), uintptr(qosHandle), uintptr(flowId), uintptr(operation), uintptr(size), uintptr(buffer), uintptr(flags), uintptr(unsafe.Pointer(overlapped)))
	ok = r0 != 0
	if ok == false {
		err = errnoErr(e1)
	}
	return
}
